### ISSUE TITLE
Taro版本3.6.4，RN版本0.70，拉模板迁移之前小程序代码，有报错

### ISSUE THREAD

**Issue by master429** [NervJS/taro-project-templates#100]
BUNDLE  ./index 

 LOG  Running "taroDemo" with {"rootTag":11,"initialProps":{}}
 ERROR  TypeError: undefined is not a function (near '..._taro.default.useLaunch...')

This error is located at:
    in Content (created by App)
    in App (created by Entry)
    in RCTView (created by View)
    in View (created by Portal.Host)
    in Portal.Host (created by Provider)
    in ThemeProvider (created by Provider)
    in LocaleProvider (created by Provider)
    in Provider (created by Entry)
    in ChildrenWrapper (created by Root)
    in _default (created by Root)
    in Root (created by RootSiblingParent)
    in RootSiblingParent (created by Entry)
    in Entry
    in RCTView (created by View)
    in View (created by AppContainer)
    in ChildrenWrapper (created by Root)
    in _default (created by Root)
    in Root (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
    in taroDemo(RootComponent)

**Comment by zhiqingchen** [comment]
3.6.4 useLaunch 未支持
https://github.com/NervJS/taro/pull/13909
