### ISSUE TITLE
远程获取V3.1版本模板始终

### ISSUE THREAD

**Issue by Dewyzee** [NervJS/taro-project-templates#30]
Taro: v1.2.16
操作系统：MacOS Catalina 10.15.4

问题复现步骤：
* taro init myApp
* React
* Typescript
* Sass
问题现象： 正在从 github:NervJS/taro-project-templates#v3.1 拉取远程模板...
会卡在这里无法创建项目

**Comment by Chen-jj** [comment]
使用 gitee 模板源或命令行科学上网
