### ISSUE TITLE
微信小程序插件项目，在微信开发者工具中报错的问题。

### ISSUE THREAD

**Issue by jzsjiale** [NervJS/taro-project-templates#5]
创建微信小程序插件项目，修改了两处的appid，其他不做任何改动，直接编译后，按官方的教程，在微信开发者工具中，导入taro插件项目根目录，微信开发者工具那边一直报未找到入口app.json的错，请问配置上是还得需要做别的改动吗？

**Comment by Garfield550** [comment]
建议提到 Taro 的 Issue 里，然后附带一些 Taro 依赖等信息。

**Comment by Garfield550** [comment]
建议提到 Taro 的 Issue 里，这边先关闭了。
