### ISSUE TITLE
github actions android debug FAILED

### ISSUE THREAD

**Issue by shuigedeng** [NervJS/taro-project-templates#50]
1. 环境 Taro v3.3.9
![image](https://user-images.githubusercontent.com/26796592/139636680-46a4742a-9def-40a4-9f9b-fbbbf81a5f06.png)

2. 异常信息
[androidx.vectordrawable:vectordrawable-animated:1.0.0] /home/runner/.gradle/caches/transforms-3/f14803a315f67746b9fb71068be927be/transformed/vectordrawable-animated-1.0.0/AndroidManifest.xml Warning:
	Package name 'androidx.vectordrawable' used in: androidx.vectordrawable:vectordrawable-animated:1.0.0, androidx.vectordrawable:vectordrawable:1.0.1.

See http://g.co/androidstudio/manifest-merger for more information about the manifest merger.

/home/runner/work/taotao-cloud-rn/android/app/src/debug/AndroidManifest.xml:12:13-88 Error:

	Attribute meta-data#org.unimodules.core.AppLoader#react-native-headless@value value=(org.unimodules.adapters.react.apploader.RNHeadlessAppLoader) from [:unimodules-react-native-adapter] AndroidManifest.xml:12:13-88

	is also present at [:expo-modules-core] AndroidManifest.xml:12:13-86 value=(expo.modules.adapters.react.apploader.RNHeadlessAppLoader).

	Suggestion: add 'tools:replace="android:value"' to <meta-data> element at AndroidManifest.xml:10:9-12:91 to override.

FAILURE: Build failed with an exception.

* What went wrong:

Execution failed for task ':app:processDebugMainManifest'.

> Manifest merger failed with multiple errors, see logs

* Try:

Run with --info or --debug option to get more log output. Run with --scan to get full insights.

**Comment by zhiqingchen** [comment]
更新到最新版试试。

参考 taro Playground 的编译过程 https://github.com/wuba/taro-playground/runs/4922036693?check_suite_focus=true
