### ISSUE TITLE
taro react-native 模版 xcode运行提示 /testApp/ios/main.jsbundle: No such file or directory

### ISSUE THREAD

**Issue by awm-liang** [NervJS/taro-project-templates#54]
模版代码拉取下来后在xcode运行一直提示找不到main.jsbuilde

CpResource /Users/Desktop/Web/testApp/ios/main.jsbundle /Users/Library/Developer/Xcode/DerivedData/taroDemo-epdbqwgfseeombdqysdlfdnkgzul/Build/Products/Debug-iphonesimulator/taroDemo.app/main.jsbundle (in target 'taroDemo' from project 'taroDemo')
    cd /Users/Desktop/Web/testApp/ios
    builtin-copy -exclude .DS_Store -exclude CVS -exclude .svn -exclude .git -exclude .hg -resolve-src-symlinks /Users/Desktop/Web/testApp/ios/main.jsbundle /Users/Library/Developer/Xcode/DerivedData/taroDemo-epdbqwgfseeombdqysdlfdnkgzul/Build/Products/Debug-iphonesimulator/taroDemo.app

error: /Users/Desktop/Web/testApp/ios/main.jsbundle: No such file or directory (in target 'taroDemo' from project 'taroDemo')

taro info
👽 Taro v3.3.15

  Taro CLI 3.3.15 environment info:
    System:
      OS: macOS 11.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 16.13.0 - /usr/local/bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 8.1.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: 3.3.15 => 3.3.15 
      @tarojs/components: 3.3.15 => 3.3.15 
      @tarojs/mini-runner: 3.3.15 => 3.3.15 
      @tarojs/react: 3.3.15 => 3.3.15 
      @tarojs/runtime: 3.3.15 => 3.3.15 
      @tarojs/taro: 3.3.15 => 3.3.15 
      @tarojs/webpack-runner: 3.3.15 => 3.3.15 
      babel-preset-taro: 3.3.15 => 3.3.15 
      eslint-config-taro: 3.3.15 => 3.3.15 
      react: ^17.0.2 => 17.0.2 
      react-native: ^0.66.0 => 0.66.3

**Comment by awm-liang** [comment]
success

**Comment by zhulichaoZW** [comment]
Xcode 打开项目 ios 目录，左侧点击项目，右侧 Build Phases Tab 中，Copy Bundle Resources 删除 main.jsbundle 文件
