### ISSUE TITLE
模板中移除 `componentWillMount` 生命周期

### ISSUE THREAD

**Issue by SyMind** [NervJS/taro-project-templates#63]
React 17 中移除 componentWillMount、componentWillReceiveProps 和 componentWillUpdate。（只有新的『UNSAFE_』生命周期名才将执行。

https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html

**Comment by SyMind** [comment]
没有文档表名该仓库目前存在的分支用途，所以我不知道该如何 pr。
@luckyadam

**Comment by Chen-jj** [comment]
done~
