### ISSUE TITLE
使用Taro react native 模板自带的github actions线上自动打包报错了，麻烦帮看一下谢谢

### ISSUE THREAD

**Issue by sp0re** [NervJS/taro-project-templates#72]
Bundle updated!
+----------------------------------------+---------+------------------------+
|                               Used plugins                                |
+----------------------------------------+---------+------------------------+
| Plugin                                 | Version | Action                 |
+----------------------------------------+---------+------------------------+
| fastlane-plugin-update_android_strings | 0.1.0   | update_android_strings |
+----------------------------------------+---------+------------------------+

[10:38:11]: Sending anonymous analytics information
[10:38:11]: Learn more at https://docs.fastlane.tools/#metrics
[10:38:11]: No personal or sensitive data is sent.
[10:38:11]: You can disable this by adding `opt_out_usage` at the top of your Fastfile
[10:38:11]: ------------------------------
[10:38:11]: --- Step: default_platform ---
[10:38:11]: ------------------------------
[10:38:11]: Driving the lane 'android assemble' 🚀
[10:38:11]: ------------------------------------
[10:38:11]: --- Step: update_android_strings ---
[10:38:11]: ------------------------------------
[10:38:11]: Update xml file success.
[10:38:11]: -----------------------------
[10:38:11]: --- Step: assemblerelease ---
[10:38:11]: -----------------------------
[10:38:11]: $ /home/runner/work/taro-test/taro-test/android/gradlew assemblerelease -p . -Papp_id=com.tarodemo -Pandroid.injected.version.code=10 -Pandroid.injected.version.name=1.0.0 -Pandroid.injected.signing.store.file=/home/runner/work/taro-test/taro-test/android/app/debug.keystore -Pandroid.injected.signing.store.*** -Pandroid.injected.signing.key.alias=androiddebugkey -Pandroid.injected.signing.key.***
+-------------------+------------------+
|             Lane Context             |
+-------------------+------------------+
| DEFAULT_PLATFORM  | android          |
| PLATFORM_NAME     | android          |
| LANE_NAME         | android assemble |
| GRADLE_BUILD_TYPE | release          |
+-------------------+------------------+
[10:38:11]: Permission denied - /home/runner/work/taro-test/taro-test/android/gradlew

+------+------------------------+-------------+
|              fastlane summary               |
+------+------------------------+-------------+
| Step | Action                 | Time (in s) |
+------+------------------------+-------------+
| 1    | default_platform       | 0           |
| 2    | update_android_strings | 0           |
| 💥   | assemblerelease        | 0           |
+------+------------------------+-------------+

[10:38:11]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

Found no similar issues. To create a new issue, please visit:
bundler: failed to load command: fastlane (/usr/local/bin/fastlane)
Errno::EACCES: [!] Permission denied - /home/runner/work/taro-test/taro-test/android/gradlew
https://github.com/fastlane/fastlane/issues/new
  /usr/lib/ruby/2.7.0/open3.rb:213:in `spawn'
  /usr/lib/ruby/2.7.0/open3.rb:213:in `popen_run'
  /usr/lib/ruby/2.7.0/open3.rb:208:in `popen2e'
  /var/lib/gems/2.7.0/gems/fastlane-2.209.1/fastlane/lib/fastlane/helper/sh_helper.rb:54:in `sh_control_output'
  /usr/lib/ruby/2.7.0/forwardable.rb:235:in `sh'
  /var/lib/gems/2.7.0/gems/fastlane-2.209.1/fastlane/lib/fastlane/helper/gradle_helper.rb:32:in `trigger'
  /var/lib/gems/2.7.0/gems/fastlane-2.209.1/fastlane/lib/fastlane/actions/gradle.rb:60:in `run'
  /var/lib/gems/2.7.0/gems/fastlane-2.209.1/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
  /var/lib/gems/2.7.0/gems/fastlane-2.209.1/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
  /var/lib/gems/2.7.0/gems/fastlane-2.209.1/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
  /var/lib/gems/2.7.0/gems/fastlane-2.209.1/fastlane/lib/fastlane/runner.rb:229:in `chdir'
  /var/lib/gems/2.7.0/gems/fastlane-2.209.1/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
  /var/lib/gems/2.7.0/gems/fastlane-2.209.1/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
  /var/lib/gems/2.7.0/gems/fastlane-2.209.1/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
  Fastfile:28:in `block (2 levels) in parsing_binding'
  /var/lib/gems/2.7.0/gems/fastlane-2.209.1/fastlane/lib/fastlane/lane.rb:33:in `call'
  /var/lib/gems/2.7.0/gems/fastlane-2.209.1/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
  /var/lib/gems/2.7.0/gems/fastlane-2.209.1/fastlane/lib/fastlane/runner.rb:45:in `chdir'
  /var/lib/gems/2.7.0/gems/fastlane-2.209.1/fastlane/lib/fastlane/runner.rb:45:in `execute'
  /var/lib/gems/2.7.0/gems/fastlane-2.209.1/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
  /var/lib/gems/2.7.0/gems/fastlane-2.209.1/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
  /var/lib/gems/2.7.0/gems/fastlane-2.209.1/fastlane/lib/fastlane/commands_generator.rb:110:in `block (2 levels) in run'
  /var/lib/gems/2.7.0/gems/commander-4.6.0/lib/commander/command.rb:[187](https://github.com/sp0re/taro-test/runs/8133145824?check_suite_focus=true#step:10:188):in `call'
  /var/lib/gems/2.7.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
  /var/lib/gems/2.7.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
  /var/lib/gems/2.7.0/gems/fastlane-2.[209](https://github.com/sp0re/taro-test/runs/8133145824?check_suite_focus=true#step:10:210).1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
  /var/lib/gems/2.7.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
  /var/lib/gems/2.7.0/gems/fastlane-2.209.1/fastlane/lib/fastlane/commands_generator.rb:354:in `run'
  /var/lib/gems/2.7.0/gems/fastlane-2.209.1/fastlane/lib/fastlane/commands_generator.rb:43:in `start'
  /var/lib/gems/2.7.0/gems/fastlane-2.209.1/fastlane/lib/fastlane/cli_tools_distributor.rb:123:in `take_off'
  /var/lib/gems/2.7.0/gems/fastlane-2.209.1/bin/fastlane:23:in `<top (required)>'
  /usr/local/bin/fastlane:23:in `load'
  /usr/local/bin/fastlane:23:in `<top (required)>'
Run `fastlane env` to append the fastlane environment to your issue
Error: Process completed with exit code 1.

**Comment by zhiqingchen** [comment]
Permission denied - /home/runner/work/taro-test/taro-test/android/gradlew

**Comment by zhiqingchen** [comment]
https://github.com/zhiqingchen/taro-test

win git 初始化后有权限问题，可搜一下解决方法
或可以用我初始化好的
