### ISSUE TITLE
v3.6-RN-0.69模板构建失败

### ISSUE THREAD

**Issue by proclml** [NervJS/taro-project-templates#85]
按官网操作：
```
yarn install
yarn upgradePeerdeps
yarn build:rn --platform android
cd android
./gradlew clean
./gradlew assembleRelease
```

报错截图如下：
![image](https://user-images.githubusercontent.com/38473196/208062956-84ea85ad-33e2-4275-b1b6-3e22b50cb44c.png)

请问是什么原因？

**Comment by proclml** [comment]
我用的taro版本是3.5

**Comment by zhiqingchen** [comment]
这个是 3.6 的模板

**Comment by zhiqingchen** [comment]
使用场景是 3.6 的 taro 不希望使用 react native 0.70
